var CONSTS = {
    BULLET_VELOCITY: 6,
    SOLDIER_VELOCITY: 4,
    SOLDIER_ATTACK_DISTANCE: 310,
    SOLDIER_SHOT_FREQUENCY: 1000,
    SOLDIER_HP: 40,
    TOWER_COOLDOWN: 10,
    TOWER_ATTACK_DISTANCE: 400,
    TOWER_SHOT_FREQUENCY: 900,
    TOWER_HP: 350,
    TOWER_BUILDING_DISTANCE: 400,
    COMMAND_CENTER_SPAWN_FREQUENCY: 2000,
    COMMAND_CENTER_SOLDIER_LIMIT: 15,
    COMMAND_CENTER_HP: 1000,
    SYNC_TIMEOUT: 100,
    FRAME_RATE: 16.7,
    UPGRADE_SPAWN_SPEED_COOLDOWN: 10
}

try {
    module.exports.CONSTS = CONSTS;
} catch (e) { }